const RULES = {
  REDEMPTION_POINT: 1,
  REDEMPTION_AMOUNT: 1,
  EXPIRE_MONTH: 1,
  FULFILLMENT_DELAY: 7,
};

const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
  ENABLED: 'ENABLED',
  EXPIRED: 'EXPIRED',
};

module.exports = { RULES, STATUS };
